FROM node:18-alpine
WORKDIR /app
COPY app.js .
ENV PORT=3000
EXPOSE 3000
ENV NODE_ENV=dev
ENV APP_NAME=DockerApp
HEALTHCHECK --interval=10s --timeout=5s --retries=3 \
CMD wget -qo- http://localhost:3000 || exit
ENTRYPOINT ["node"]
CMD ["app.js"]