pipeline {
    agent any

    environment {
        DOCKER_USER = "kartik71845"
        IMAGE_NAME  = "my_app"
    }

    stages {

        stage('Prepare_Tag ') {
            steps {
                script {
                    // Take first 7 characters of commit SHA
                    env.IMAGE_TAG = env.GIT_COMMIT.take(7)
                    echo "Using tag: ${env.IMAGE_TAG}"
                }
            }
        }

        stage('Build') {
            steps {
                dir('pipeline2') {
                 sh "docker build -t ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG} ."   
                }
            }
        }

        stage('Test') {
            steps {
                sh ''' 
                docker rm -f node_app || true
                docker run -d -p 4000:3000 --name node_app ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG} 
                sleep 5
                docker exec node_app curl http://localhost:3000
                docker rm -f node_app 
                '''
            }
        }

        stage('Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhubcreds',
                    usernameVariable: 'DOCKER_USER_VAR',
                    passwordVariable: 'DOCKER_PASS_VAR'
                )]) {
                    sh """
                    echo \$DOCKER_PASS_VAR | docker login -u \$DOCKER_USER_VAR --password-stdin
                    docker push ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }
    }
}
